### ISSUE TITLE
Directory structure issue?

### ISSUE THREAD

**Issue by Wack0** [jmechnich/s3turbo#1]
It would be preferable, at least in my view, to have the standard DOS-style `FILE.EXT`, where appropriate, instead of the way it's stored in the FAT directory structure (`FILE`` `` ``EXT`).

I'd try to implement this myself, but Python isn't my forté.

**Comment by jmechnich** [comment]
Hi,

I don't necessarily disagree and at some point I had it coded like that but the way I look at it by now, the filenames are used by the S3 as 11 character filenames in contrast to 8 character name + 3 character extension. In the last couple of days I changed a lot of the code which is not yet pushed, preparing for implementing write support. I will have another look at how to convert the filenames and get back to you.

**Comment by jmechnich** [comment]
So, I have added image writing to `s3img` now and made a few changes to the extension handling as well. For a number of known extensions (notably PRG, LOD and TXL), whitespace will be stripped from the file name and the extension appended with a dot. When files are added to the image, this procedure will be reversed. For testing you could try:

```
# extract contents of image
s3img read -e mydir myimage.img
# list extracted files and directories, could also add more files
find mydir
# write new image
s3img write -a mydir newimage.img
# list image contents
s3image read -c newimage.img
```

One issue I have noticed is that at least for user programs, LOADER.LOD will not accept PRG files with a lowercase filename. My solution was to change the name to uppercase before creating the image file but maybe this is something that could/should be done by `s3img`. It might be more convenient on case-insensitive file systems like on Mac or possibly Windows (?).

**Comment by bijlevel** [comment]
Hi jmechnich,
I'm interested of using this software to "unlock" my S3 Turbo, but I don't have a clue how to start with your files or how to communicate with the S3 from my computer. Or are all commands send over MIDI? I'm on a Mac which has (as I understand) Python installed by default. So should I download your files as text and try to compile them with Python? If I succeed, how does the program then work with the S3? As you may have noticed I'm a novice regarding this stuff. I am though a rather proficient in MIDI Sysex and use CTRLR ([http://ctrlr.org/](url)) to make iMIDI-editors for my older gear, like Yamaha TX7 ([http://ctrlr.org/yamaha-tx7-v1-0-panel/](url)) , but for those synthesizer sysex is well documented, especially the data format, so one can locate in de datafile all the parameters and their value and in this way control a synth via sysex.
Anyway, thanks in advance!

Best regards, Sjoerd W. Bijleveld, The Netherlands

**Comment by jmechnich** [comment]
Hi Sjoerd,

the `s3img` and `s3floppy` commands are for handling floppy disks and images on your computer, so you are probably interested only in what `s3midi` does. It implements MIDI SysEx commands described in the S-series manual, but unfortunately this implementation seems to be incomplete. I am not sure if the available functions are sufficient for writing a CTRLR interface for the S-series but you should be able to replicate all of `s3midi`'s commands with the right sequence of SysEx messages. There should be some notes about the protocol in the repository.

What is doable right now is to browse the S-series' internal file system and download files (samples, presets, sound and effects library, and more). Partly, the file formats are known and should be described in one of the text files if so. Uploading files does not work so far (except for Standard MIDI Sample transfer), so bi-directional editing is not really an option. I am still looking at my S3's ROM source code hoping to find some undocumented features to make this possible.

In any case, if you want to try `s3midi` on your Mac, you would need the pypm MIDI library first. So far I have only tested the software on Linux but it should also work on Mac.

I am closing this thread here, if you have more questions or issues, don't hesitate to open a new topic.

Regards,
Joerg

**Comment by bijlevel** [comment]
OK, thanks for the reply and information! I will try to find out more and hopefully then things work out for me.
